<?php
$GLOBALS['TYPO3_CONF_VARS']['DB']['database'] = getenv('REMOTE_ADDR');
$GLOBALS['TYPO3_CONF_VARS']['DB']['host'] = getenv('DB_PORT_3306_TCP_ADDR');
$GLOBALS['TYPO3_CONF_VARS']['DB']['port'] = getenv('DB_PORT_3306_TCP_PORT');
$GLOBALS['TYPO3_CONF_VARS']['DB']['username'] = getenv('DB_ENV_USER');
$GLOBALS['TYPO3_CONF_VARS']['DB']['password'] = getenv('DB_ENV_PASS');

$GLOBALS['TYPO3_CONF_VARS']['BE']['installToolPassword'] = ''; // @todo fill with usefull default or env ore autogenerated?
